delta: 0.02
travel_height: 0.30
pick_height: 0.12
drop_height: 0.22
num_objects: 5
k_nearest_obstacles: 3
grasp_radius: 0.03
drop_radius: 0.04
unsafe_action_behavior: NOOP
missing_before_rescan: 3
rescan_interval_steps: 20
tool_orientation: [3.14159, 0.0, 0.0]
workspace:
  x_min: 0.00
  x_max: 0.60
  y_min: -0.30
  y_max: 0.30
  z_min: 0.05
  z_max: 0.40
obstacle_margin: 0.03
motion_profile:
  acceleration: 0.6
  velocity: 0.20
gripper:
  pin: 0
